#!/bin/bash
#
# cleanlib32 - Remove unneeded lib32 packages from your Arch Linux system
#
#   Copyright (C) 2012 josephgbr <rafael.f.f1@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

PROGRAM=cleanlib32
VERSION=0.1

PACMAN="/usr/bin/pacman"
SUDO="/usr/bin/sudo"

version()
{
cat << EOMSG

${PROGRAM} v${VERSION}
Copyright (C) 2012-2012 josephgbr <rafael.f.f1@gmail.com>
This program may be freely redistributed under the terms \
of the GNU General Public License.

EOMSG

exit 0
}

usage() {
cat << EOMSG
usage: $PROGRAM [operation]
operations:
        $PROGRAM {-h --help}
        $PROGRAM {-V --version}

Use $PROGRAM to easily remove lib32 packages marked as
"installed as dependency" of another, but not need anymore.
Target packages will be displayed and will  $PROGRAM will
give you a chance to cancel, in case you do not want to
remove at least one of them.

Note that lib32 packages not marked as dependency will not
be removed.

EOMSG

exit 0
}

# These two functions were based on makepkg from package 'pacman'
GREEN='\033[32m';RED='\033[31m';ALL_OFF='\033[m'
msg() {
	local mesg=$1; shift
	printf "${GREEN}==>${ALL_OFF} ${mesg}\n" "$@" >&2
}
error() {
	local mesg=$1; shift
	printf "${RED}==> ERROR:${ALL_OFF} ${mesg}" "$@" >&2
}

if [ ! "$1" == "" ]; then
	case $1 in
	 -h|--help) usage;;
	 -V|--version) version;;
	 *) error "Invalid option: $PROGRAM"; exit 1;;
	esac
fi

# Try to gather all targets. If there is none, then quit
msg "Gathering list of uneeded packages to be uninstalled..."
PACKAGES=$(echo $(${PACMAN} -Qtd | grep lib32- | cut -d' ' -f1))
if test ! "${PACKAGES}"; then
	printf "No uneeded lib32 package installed. There is nothing to do. Leaving...\n"
fi

# Display targets to be removed, so user can decide wether this script should continue
msg "Packages that will be uninstalled:"
printf "\n"
for pkg in ${PACKAGES}; do printf "   ${pkg}\n"; done
printf "\n"
printf "Press N key to NOT uninstallation right now or any other key to continue.\n(waiting for an answer from user...)"
read opt
opt=$(echo ${opt} | tr [:lower:] [:upper:])
[ "${opt}" == "N" ] && exit 0

# Not going to quit, so we are going to uninstall software, if user has root permissions.
if [ "$(id -u)" == "0" ]; then
	msg "Removing packages..."
	${PACMAN} -R ${PACKAGES} --noconfirm
elif [ -x ${SUDO} ]; then
	msg "Removing packages with sudo..."
	${SUDO} ${PACMAN} -R ${PACKAGES} --noconfirm
else
	error "You don't have root permission to uninstall packages."
fi

